### PR TITLE
bump kernel to 6.12.4-1

### PR DESCRIPTION
**Pull request by mkurz**
signed off commit

### CODE REVIEW

**Comment by nikwest** [comment]
just trying this out as I'm stuck with my arch asahi server and want to upgrade the kernel. I could compile it, but for installation  you have added a dependency to mesa-asahi, which I haven't installed. Is this required? I guess it's more like if you have mesa installed you should have at least that version?

**Comment by mkurz** [comment]
>  I guess it's more like if you have mesa installed you should have at least that version?

Yeah, probably. You can try to remove mesa from the pkgbuild and try again.

**Comment by nikwest** [comment]
yeah, that worked. Probably better to put it in 
optdepends

**Comment by mkurz** [comment]
Yeah probably makes sense to put it into optdepends + make it a required dependency in asahi-desktop-meta however also

**Comment by mkurz** [comment]
Already in https://github.com/asahi-alarm/PKGBUILDs.

@nikwest I removed the dependency to mesa-asahi in the kernel package, but added is a dependency to the asahi-desktop-meta package. See https://github.com/asahi-alarm/PKGBUILDs/pull/53

**Pull request closed without merging**
